Some work on porting dpdgraph to the current Coq
I'm not sure where to get Projection.constant from.  @mattam82, is there
something I need to `open`?

Also, when I `make file-dep-graphs/hott-lib.dpd`, I get

```bash
coqmktop  -opt -o coqthmdep searchdepend.cmx graphdepend.cmx
File "/tmp/coqmain9fb047.ml", line 1:
Error: Cannot find file threads.cmxa
```

Any ideas how to fix this?